USE [master]
GO

/****** Object:  Database [iTrellis_ToDo]    Script Date: 04/26/2015 20:17:39 ******/
CREATE DATABASE [iTrellis_ToDo] ON  PRIMARY 
( NAME = N'iTrellis_ToDo', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\iTrellis_ToDo.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'iTrellis_ToDo_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\iTrellis_ToDo_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [iTrellis_ToDo] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [iTrellis_ToDo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [iTrellis_ToDo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [iTrellis_ToDo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [iTrellis_ToDo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [iTrellis_ToDo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [iTrellis_ToDo] SET ARITHABORT OFF 
GO

ALTER DATABASE [iTrellis_ToDo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [iTrellis_ToDo] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [iTrellis_ToDo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [iTrellis_ToDo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [iTrellis_ToDo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [iTrellis_ToDo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [iTrellis_ToDo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [iTrellis_ToDo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [iTrellis_ToDo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [iTrellis_ToDo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [iTrellis_ToDo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [iTrellis_ToDo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [iTrellis_ToDo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [iTrellis_ToDo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [iTrellis_ToDo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [iTrellis_ToDo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [iTrellis_ToDo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [iTrellis_ToDo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [iTrellis_ToDo] SET  READ_WRITE 
GO

ALTER DATABASE [iTrellis_ToDo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [iTrellis_ToDo] SET  MULTI_USER 
GO

ALTER DATABASE [iTrellis_ToDo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [iTrellis_ToDo] SET DB_CHAINING OFF 
GO

