//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTrellis_ToDo.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoList
    {
        public ToDoList()
        {
            this.ToDoTaskItems = new HashSet<ToDoTaskItem>();
        }
    
        public int ID { get; set; }
        public string ListName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedByUserID { get; set; }
    
        public virtual ICollection<ToDoTaskItem> ToDoTaskItems { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
